### ISSUE TITLE
카테고리 고정된 스트링 값 사용 

### ISSUE THREAD

**Issue by heyman333** [depromeet/warming-up-team2-server#57]
- 생활용품
- 육아용품
- 문화 
- 건강
- 미등록 

위 5가지만 사용하게 되면 문제 있을까요?

위대로라면 카테고리 조회 및 생성 도 없어도 될거같은데요

**Comment by junhaesung** [comment]
좋습니다~

**Comment by junhaesung** [comment]
한글 그대로 사용하나요?

**Comment by kscory** [comment]
영어로 사용해여!

**Comment by junhaesung** [comment]
영어로 사용하면, 영어-한글 사이 매핑해야되는데, 괜찮으세요?

**Comment by heyman333** [comment]
@Lee-KyungSeok
@junhaesung 

한글 그대로 사용하면 카테코리라는 필드로 그대로 넘기고 받을 수 있을거같은데요 한글이 더 편하지 않을까요 ㅎㅎ

**Comment by kscory** [comment]
다 좋습니다~ 일단 빠르게 한글로 가죠

**Comment by junhaesung** [comment]
'미등록' 도 화면에 표시하나요?

**Comment by heyman333** [comment]
@junhaesung 네 미등록도 표시 됩니다~

**Comment by junhaesung** [comment]
@heyman333 그럼 다음 중 어떤게 더 편하세요?
'미등록'이라는 단어가 변경될 수 있다고 하면, 1안이 더 좋은거같습니다
의견 부탁드립니다
1. 
```
"category": null
```
2. 
```
"category": "미등록"
```

참고로 현재 구현은 1번으로 되어있습니다
